#!/usr/bin/env python3
"""
Enhanced cfDNA PCA analysis using detailed size bin distributions.
Works with data generated by extract_detailed_cfDNA_sizes.py.

This version is designed to be broadly reusable across projects.
User-editable settings are grouped under USER SETTINGS.
"""

import argparse
import glob
import os
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.patches import Circle
from scipy.stats import kruskal, mannwhitneyu, pearsonr
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

# ============================================================================
# USER SETTINGS (edit these when adapting to a new project)
# ============================================================================
# Input directory containing size distribution/count CSVs. Recursive search used.
DATA_DIRECTORY = r"/mnt/d/coronary_cfDNA/cfDNA_detailed_size_analysis"

# Output directory for figures and summary files.
OUTPUT_DIRECTORY = r"/mnt/d/coronary_cfDNA/PCA_results_detailed"

# Fragment types to analyze. These names are used during file discovery.
FRAGMENT_TYPES = ["mononucleosomal", "dinucleosomal", "trinucleosomal", "hmw"]

# Recursive file search templates. Keep these unless your naming is very different.
# Available placeholders: {fragment_type}, {suffix}
FILE_SEARCH_PATTERNS = [
    "**/{fragment_type}_{suffix}",
    "**/*{fragment_type}*{suffix}",
    "**/{fragment_type}*{suffix}",
]

# Preferred column names if your input already stores groups directly.
GROUP_COLUMN_CANDIDATES = ["group", "condition", "cohort", "class", "label"]

# Preferred column names for sample IDs used in labels and fallback group inference.
SAMPLE_NAME_COLUMN_CANDIDATES = ["bam_file", "sample", "sample_name", "filename", "file", "id"]

# Regex rules for inferring group from sample names when no group column exists.
# EDIT THESE RULES for your own naming convention.
GROUP_RULES = [
    {"label": "stemi", "pattern": r"^cor_.*barcode[_-]?(0[1-5])\b"},
    {"label": "recovery", "pattern": r"^rec_.*barcode[_-]?(0[6-9]|10)\b"},
    {"label": "control", "pattern": r"^con_.*barcode[_-]?(1[1-5])\b"},
]

# Optional preferred order in legends/plots. Extra groups are appended alphabetically.
GROUP_ORDER = ["stemi", "recovery", "control", "unknown"]

# Optional color overrides. Any unseen groups get automatic colors.
GROUP_COLOR_MAP = {
    "stemi": "#d62728",
    "recovery": "#1f77b4",
    "control": "#2ca02c",
    "unknown": "#7f7f7f",
}

# Drop samples assigned to unknown group before PCA/statistics.
DROP_UNKNOWN_GROUP = False
# ============================================================================


def parse_args():
    """Optional CLI overrides for paths/settings."""
    parser = argparse.ArgumentParser(description="cfDNA PCA analysis for detailed size bins")
    parser.add_argument("--data-dir", default=DATA_DIRECTORY, help="Input directory (recursive search)")
    parser.add_argument("--output-dir", default=OUTPUT_DIRECTORY, help="Output directory")
    parser.add_argument(
        "--fragments",
        default=",".join(FRAGMENT_TYPES),
        help="Comma-separated fragment types (e.g. mononucleosomal,dinucleosomal,hmw)",
    )
    parser.add_argument(
        "--drop-unknown",
        action="store_true",
        default=DROP_UNKNOWN_GROUP,
        help="Drop samples assigned to unknown group",
    )
    return parser.parse_args()


def normalize_group_label(value):
    """Normalize any group label to lowercase text."""
    if pd.isna(value):
        return "unknown"
    return str(value).strip().lower()


def get_ordered_groups(groups):
    """Return groups in preferred display order, then extras alphabetically."""
    observed = {g for g in groups if pd.notna(g)}
    ordered = [group for group in GROUP_ORDER if group in observed]
    remaining = sorted([group for group in observed if group not in GROUP_ORDER])
    return ordered + remaining


def build_group_color_map(groups):
    """Use configured colors when available, auto-assign colors for unseen groups."""
    color_map = dict(GROUP_COLOR_MAP)
    extras = [g for g in get_ordered_groups(groups) if g not in color_map]
    if extras:
        palette = plt.cm.tab20(np.linspace(0, 1, max(3, len(extras))))
        for idx, group in enumerate(extras):
            rgb = palette[idx % len(palette)][:3]
            color_map[group] = "#%02x%02x%02x" % tuple(int(255 * c) for c in rgb)
    return color_map


def infer_group_from_sample_name(sample_name):
    """
    Infer group from sample naming convention using GROUP_RULES.

    Edit GROUP_RULES in USER SETTINGS for other projects.
    """
    normalized = os.path.splitext(os.path.basename(str(sample_name)))[0].lower()
    for rule in GROUP_RULES:
        if re.search(rule["pattern"], normalized):
            return rule["label"]
    return "unknown"


def find_matching_file(data_dir, fragment_type, suffix):
    """Find a file using recursive glob patterns."""
    matches = []
    for pattern_template in FILE_SEARCH_PATTERNS:
        pattern = pattern_template.format(fragment_type=fragment_type, suffix=suffix)
        matches.extend(glob.glob(os.path.join(data_dir, pattern), recursive=True))

    matches = sorted(set(matches))
    if not matches:
        return None

    if len(matches) > 1:
        print(f"Warning: multiple matches for {fragment_type}_{suffix}. Using first:")
        for candidate in matches[:5]:
            print(f"  - {candidate}")

    return matches[0]


def get_sample_names(df):
    """Extract sample names from common columns, fallback to index."""
    for col in SAMPLE_NAME_COLUMN_CANDIDATES:
        if col in df.columns:
            return df[col].astype(str).values, col
    return df.index.astype(str).values, "index"


def assign_groups(df, sample_names):
    """Assign groups from a group column, else infer from sample names."""
    for col in GROUP_COLUMN_CANDIDATES:
        if col in df.columns:
            groups = df[col].apply(normalize_group_label).values
            if len(pd.unique(groups)) > 1:
                print(f"Using groups from column '{col}'")
                return groups, f"column:{col}"

    groups = np.array([infer_group_from_sample_name(name) for name in sample_names])
    print("Using groups inferred from sample names via GROUP_RULES")
    return groups, "inferred"


def draw_group_circle(ax, x_values, y_values, color):
    """Draw a dashed enclosing circle around a group on a PCA scatter plot."""
    if len(x_values) == 0:
        return

    center_x = float(np.mean(x_values))
    center_y = float(np.mean(y_values))
    distances = np.sqrt((x_values - center_x) ** 2 + (y_values - center_y) ** 2)

    base_radius = float(np.max(distances)) if len(distances) > 0 else 0.0
    padding = max(0.12, base_radius * 0.15)
    radius = base_radius + padding

    circle = Circle(
        (center_x, center_y),
        radius,
        fill=False,
        edgecolor=color,
        linewidth=1.8,
        linestyle="--",
        alpha=0.85,
    )
    ax.add_patch(circle)


def ensure_output_directory():
    """Create output directory if it does not exist."""
    if not os.path.exists(OUTPUT_DIRECTORY):
        os.makedirs(OUTPUT_DIRECTORY)
        print(f"Created output directory: {OUTPUT_DIRECTORY}")


def load_fragment_data(fragment_type):
    """
    Load detailed size distribution and count data for one fragment type.

    Returns:
        tuple: (percentage_df, count_df) or (None, None)
    """
    percentage_file = find_matching_file(DATA_DIRECTORY, fragment_type, "size_distributions.csv")
    count_file = find_matching_file(DATA_DIRECTORY, fragment_type, "size_counts.csv")

    if not percentage_file:
        print(f"Warning: percentage file not found for '{fragment_type}' in {DATA_DIRECTORY}")
        return None, None

    if not count_file:
        print(f"Warning: count file not found for '{fragment_type}' in {DATA_DIRECTORY}")
        return None, None

    try:
        percentage_df = pd.read_csv(percentage_file)
        count_df = pd.read_csv(count_file)

        print(f"Loaded {fragment_type} data:")
        print(f"  Percentage file: {percentage_file}")
        print(f"  Count file: {count_file}")
        print(f"  Percentage data: {percentage_df.shape}")
        print(f"  Count data: {count_df.shape}")

        size_columns = [col for col in percentage_df.columns if col.endswith("bp")]
        if size_columns:
            print(f"  Size columns: {len(size_columns)} ({size_columns[0]} to {size_columns[-1]})")
        else:
            print("  Warning: no columns ending with 'bp' were found")

        return percentage_df, count_df

    except Exception as e:
        print(f"Error loading {fragment_type} data: {e}")
        return None, None


def perform_fragment_pca(percentage_df, count_df, fragment_type):
    """
    Perform PCA analysis on detailed size bin data.

    Returns:
        dict: Results including PCA components, variance, stats, etc.
    """
    print(f"\n--- PCA Analysis: {fragment_type} ---")

    size_columns = [col for col in percentage_df.columns if col.endswith("bp")]
    if len(size_columns) < 3:
        print(f"Warning: only {len(size_columns)} size bins found for {fragment_type}")
        print("PCA requires at least 3 features for meaningful analysis")
        return None

    print(f"Using {len(size_columns)} size bin features")

    X = percentage_df[size_columns].values
    sample_names, sample_name_source = get_sample_names(percentage_df)
    groups, group_source = assign_groups(percentage_df, sample_names)

    size_values = np.array([int(col.replace("bp", "").split("_")[-1]) for col in size_columns])
    mean_fragment_sizes = np.average(X, axis=1, weights=size_values)

    unknown_mask = groups == "unknown"
    unknown_count = np.sum(unknown_mask)
    print(f"Assigned groups: {pd.Series(groups).value_counts().to_dict()}")
    print(f"Sample name source: {sample_name_source}; group source: {group_source}")
    if unknown_count > 0:
        print(f"Warning: {unknown_count} samples could not be assigned to a known group")

    if "total_fragments_all" in count_df.columns:
        sequencing_depths = count_df["total_fragments_all"].values
    elif "total_fragments" in count_df.columns:
        sequencing_depths = count_df["total_fragments"].values
    else:
        count_size_columns = [col for col in count_df.columns if col.endswith("bp")]
        sequencing_depths = np.sum(count_df[count_size_columns].values, axis=1)

    if DROP_UNKNOWN_GROUP and unknown_count > 0:
        keep_mask = ~unknown_mask
        if np.sum(keep_mask) < 4:
            print("Warning: not enough samples remain after dropping unknown groups")
            return None
        X = X[keep_mask]
        sample_names = sample_names[keep_mask]
        groups = groups[keep_mask]
        sequencing_depths = sequencing_depths[keep_mask]
        mean_fragment_sizes = mean_fragment_sizes[keep_mask]
        print(f"Dropped unknown samples. Remaining groups: {pd.Series(groups).value_counts().to_dict()}")

    if X.shape[0] < 4:
        print(f"Warning: only {X.shape[0]} samples - need at least 4 for PCA")
        return None

    column_std = np.std(X, axis=0)
    valid_columns = column_std > 1e-10
    if np.sum(valid_columns) < 2:
        print(f"Warning: only {np.sum(valid_columns)} columns with variance")
        return None

    X_filtered = X[:, valid_columns]
    size_columns_filtered = [size_columns[i] for i in range(len(size_columns)) if valid_columns[i]]
    print(f"After filtering: {X_filtered.shape[1]} features with variance")

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_filtered)

    n_components = min(X_scaled.shape[0] - 1, X_scaled.shape[1], 10)
    pca = PCA(n_components=n_components)
    X_pca = pca.fit_transform(X_scaled)

    explained_var = pca.explained_variance_ratio_
    cumulative_var = np.cumsum(explained_var)

    pc1_depth_corr, pc1_depth_p = pearsonr(X_pca[:, 0], sequencing_depths)
    pc2_depth_corr, pc2_depth_p = pearsonr(X_pca[:, 1], sequencing_depths)

    print(f"PC1 explains {explained_var[0]:.1%} of variance")
    print(f"PC2 explains {explained_var[1]:.1%} of variance")
    print(f"PC1+PC2 explains {cumulative_var[1]:.1%} of variance")

    group_types = np.unique(groups)
    stats_results = {}

    if len(group_types) == 2:
        for pc_idx in range(min(3, len(explained_var))):
            group1_data = X_pca[groups == group_types[0], pc_idx]
            group2_data = X_pca[groups == group_types[1], pc_idx]
            if len(group1_data) > 0 and len(group2_data) > 0:
                stat, p_val = mannwhitneyu(group1_data, group2_data, alternative="two-sided")
                stats_results[f"PC{pc_idx + 1}"] = {
                    "test": "mwu",
                    "statistic": stat,
                    "p_value": p_val,
                    "significant": p_val < 0.05,
                }
                sig = "***" if p_val < 0.001 else "**" if p_val < 0.01 else "*" if p_val < 0.05 else ""
                print(f"PC{pc_idx + 1} Mann-Whitney U test p-value: {p_val:.4f} {sig}")
    elif len(group_types) > 2:
        for pc_idx in range(min(3, len(explained_var))):
            per_group_data = [X_pca[groups == group_name, pc_idx] for group_name in group_types]
            if all(len(values) > 0 for values in per_group_data):
                stat, p_val = kruskal(*per_group_data)
                stats_results[f"PC{pc_idx + 1}"] = {
                    "test": "kruskal",
                    "statistic": stat,
                    "p_value": p_val,
                    "significant": p_val < 0.05,
                }
                sig = "***" if p_val < 0.001 else "**" if p_val < 0.01 else "*" if p_val < 0.05 else ""
                print(f"PC{pc_idx + 1} Kruskal-Wallis p-value: {p_val:.4f} {sig}")

    print("\nSequencing Depth Correlations:")
    pc1_sig = "***" if pc1_depth_p < 0.001 else "**" if pc1_depth_p < 0.01 else "*" if pc1_depth_p < 0.05 else ""
    pc2_sig = "***" if pc2_depth_p < 0.001 else "**" if pc2_depth_p < 0.01 else "*" if pc2_depth_p < 0.05 else ""
    print(f"PC1 vs Depth: r = {pc1_depth_corr:.3f}, p = {pc1_depth_p:.4f} {pc1_sig}")
    print(f"PC2 vs Depth: r = {pc2_depth_corr:.3f}, p = {pc2_depth_p:.4f} {pc2_sig}")

    sil_score = None
    if len(np.unique(groups)) > 1 and X_pca.shape[1] >= 2:
        try:
            sil_score = silhouette_score(X_pca[:, :2], groups)
            print(f"Silhouette score (PC1+PC2): {sil_score:.3f}")
        except Exception as e:
            print(f"Warning: silhouette score failed ({e})")

    feature_contributions = {}
    for pc_idx in range(min(2, len(pca.components_))):
        pc_loadings = pca.components_[pc_idx]
        top_indices = np.argsort(np.abs(pc_loadings))[-5:][::-1]

        feature_contributions[f"PC{pc_idx + 1}"] = []
        for idx in top_indices:
            size_bin = size_columns_filtered[idx]
            loading = pc_loadings[idx]
            size_bp = size_bin.replace(f"{fragment_type}_", "").replace("bp", "")
            feature_contributions[f"PC{pc_idx + 1}"].append(
                {
                    "size_bin": size_bp,
                    "loading": loading,
                    "abs_loading": abs(loading),
                }
            )

        print(f"PC{pc_idx + 1} top contributors:")
        for contrib in feature_contributions[f"PC{pc_idx + 1}"]:
            print(f"  {contrib['size_bin']}bp: {contrib['loading']:+.3f}")

    return {
        "pca": pca,
        "X_pca": X_pca,
        "X_scaled": X_scaled,
        "scaler": scaler,
        "explained_variance": explained_var,
        "cumulative_variance": cumulative_var,
        "groups": groups,
        "sample_names": sample_names,
        "group_source": group_source,
        "size_columns": size_columns_filtered,
        "stats_results": stats_results,
        "silhouette_score": sil_score,
        "feature_contributions": feature_contributions,
        "fragment_type": fragment_type,
        "sequencing_depths": sequencing_depths,
        "pc1_depth_correlation": pc1_depth_corr,
        "pc2_depth_correlation": pc2_depth_corr,
        "pc1_depth_p_value": pc1_depth_p,
        "pc2_depth_p_value": pc2_depth_p,
        "mean_fragment_sizes": mean_fragment_sizes,
    }


def create_comprehensive_plots(results):
    """Create comprehensive PCA visualization plots."""
    if not results:
        return

    fragment_type = results["fragment_type"]
    fig = plt.figure(figsize=(20, 16))

    ax1 = plt.subplot(3, 3, 1)
    unique_groups = get_ordered_groups(results["groups"])
    color_map = build_group_color_map(unique_groups)

    for group in unique_groups:
        mask = results["groups"] == group
        x_group = results["X_pca"][mask, 0]
        y_group = results["X_pca"][mask, 1]
        color = color_map.get(group, "#9467bd")

        plt.scatter(x_group, y_group, c=color, label=f"{group} (n={np.sum(mask)})", alpha=0.7, s=60)
        draw_group_circle(ax1, x_group, y_group, color)

    plt.xlabel(f"PC1 ({results['explained_variance'][0]:.1%})")
    plt.ylabel(f"PC2 ({results['explained_variance'][1]:.1%})")
    plt.title(f"{fragment_type} - PCA Scatter Plot")
    plt.legend()
    plt.grid(True, alpha=0.3)

    ax2 = plt.subplot(3, 3, 2)
    pc_numbers = range(1, len(results["explained_variance"]) + 1)
    plt.plot(pc_numbers, results["explained_variance"] * 100, "bo-", linewidth=2, markersize=6)
    plt.xlabel("Principal Component")
    plt.ylabel("Explained Variance (%)")
    plt.title(f"{fragment_type} - Scree Plot")
    plt.xticks(pc_numbers)
    plt.grid(True, alpha=0.3)

    ax2_twin = ax2.twinx()
    ax2_twin.plot(pc_numbers, results["cumulative_variance"] * 100, marker="o", linestyle="-", color="red", linewidth=2)
    ax2_twin.set_ylabel("Cumulative Variance (%)", color="red")
    ax2_twin.tick_params(axis="y", labelcolor="red")

    ax3 = plt.subplot(3, 3, 3)
    pc1_data = []
    group_labels = []
    for group in unique_groups:
        mask = results["groups"] == group
        pc1_data.append(results["X_pca"][mask, 0])
        group_labels.append(group)
    plt.boxplot(pc1_data, tick_labels=group_labels)
    plt.ylabel("PC1 Score")
    plt.title(f"{fragment_type} - PC1 Distribution")
    plt.grid(True, alpha=0.3)

    ax4 = plt.subplot(3, 3, 4)
    pc2_data = []
    for group in unique_groups:
        mask = results["groups"] == group
        pc2_data.append(results["X_pca"][mask, 1])
    plt.boxplot(pc2_data, tick_labels=group_labels)
    plt.ylabel("PC2 Score")
    plt.title(f"{fragment_type} - PC2 Distribution")
    plt.grid(True, alpha=0.3)

    ax5 = plt.subplot(3, 3, 5)
    pc1_loadings = results["pca"].components_[0, :]
    pc2_loadings = results["pca"].components_[1, :]
    size_values_loadings = np.array([int(col.replace("bp", "").split("_")[-1]) for col in results["size_columns"]])

    scatter = ax5.scatter(
        pc1_loadings,
        pc2_loadings,
        c=size_values_loadings,
        cmap="coolwarm",
        s=60,
        alpha=0.8,
        edgecolors="black",
        linewidth=0.5,
    )
    cbar = plt.colorbar(scatter, ax=ax5, shrink=0.8)
    cbar.set_label("Fragment Size (bp)", rotation=270, labelpad=20)

    plt.xlabel("PC1 Loading")
    plt.ylabel("PC2 Loading")
    plt.title(f"{fragment_type} - PC Loadings\n(Colored by Fragment Size)")
    plt.axhline(y=0, color="black", linestyle="-", alpha=0.3)
    plt.axvline(x=0, color="black", linestyle="-", alpha=0.3)
    plt.grid(True, alpha=0.3)

    if results["X_pca"].shape[1] > 2:
        ax6 = plt.subplot(3, 3, 6)
        for group in unique_groups:
            mask = results["groups"] == group
            x_group = results["X_pca"][mask, 0]
            y_group = results["X_pca"][mask, 2]
            color = color_map.get(group, "#9467bd")
            plt.scatter(x_group, y_group, c=color, label=f"{group}", alpha=0.7, s=60)
            draw_group_circle(ax6, x_group, y_group, color)

        plt.xlabel(f"PC1 ({results['explained_variance'][0]:.1%})")
        plt.ylabel(f"PC3 ({results['explained_variance'][2]:.1%})")
        plt.title(f"{fragment_type} - PC1 vs PC3")
        plt.legend()
        plt.grid(True, alpha=0.3)

    ax7 = plt.subplot(3, 3, 7)
    ax7.axis("off")

    stats_text = f"{fragment_type} Analysis Summary:\n\n"
    stats_text += f"Samples: {results['X_pca'].shape[0]}\n"
    stats_text += f"Size Bins: {len(results['size_columns'])}\n"
    stats_text += f"Group source: {results['group_source']}\n"
    stats_text += f"PC1 Variance: {results['explained_variance'][0]:.1%}\n"
    stats_text += f"PC2 Variance: {results['explained_variance'][1]:.1%}\n"
    stats_text += f"PC1+PC2 Total: {results['cumulative_variance'][1]:.1%}\n\n"

    if results["silhouette_score"] is not None:
        stats_text += f"Silhouette Score: {results['silhouette_score']:.3f}\n\n"

    stats_text += "Depth Correlations:\n"
    pc1_sig = "***" if results["pc1_depth_p_value"] < 0.001 else "**" if results["pc1_depth_p_value"] < 0.01 else "*" if results["pc1_depth_p_value"] < 0.05 else ""
    pc2_sig = "***" if results["pc2_depth_p_value"] < 0.001 else "**" if results["pc2_depth_p_value"] < 0.01 else "*" if results["pc2_depth_p_value"] < 0.05 else ""
    stats_text += f"PC1-Depth: r={results['pc1_depth_correlation']:.3f} {pc1_sig}\n"
    stats_text += f"PC2-Depth: r={results['pc2_depth_correlation']:.3f} {pc2_sig}\n\n"

    if results["stats_results"]:
        stats_text += "Group Separation Tests:\n"
        for pc, stats in results["stats_results"].items():
            sig_marker = "***" if stats["p_value"] < 0.001 else "**" if stats["p_value"] < 0.01 else "*" if stats["p_value"] < 0.05 else ""
            stats_text += f"{pc} ({stats.get('test', 'mwu')}): p={stats['p_value']:.4f} {sig_marker}\n"

    ax7.text(0.05, 0.95, stats_text, transform=ax7.transAxes, fontsize=11, verticalalignment="top", fontfamily="monospace")

    ax8 = plt.subplot(3, 3, 8)
    if "PC1" in results["feature_contributions"]:
        contrib_data = results["feature_contributions"]["PC1"]
        sizes = [c["size_bin"] for c in contrib_data]
        loadings = [c["loading"] for c in contrib_data]

        plt.bar(range(len(sizes)), loadings, color=["red" if x < 0 else "blue" for x in loadings], alpha=0.7)
        plt.xlabel("Top Size Bins")
        plt.ylabel("PC1 Loading")
        plt.title(f"{fragment_type} - PC1 Top Contributors")
        plt.xticks(range(len(sizes)), sizes, rotation=45)
        plt.axhline(y=0, color="black", linestyle="-", alpha=0.3)

    ax9 = plt.subplot(3, 3, 9)
    depths = results["sequencing_depths"]
    scatter = plt.scatter(
        results["X_pca"][:, 0],
        results["X_pca"][:, 1],
        c=depths,
        cmap="plasma",
        s=80,
        alpha=0.8,
        edgecolors="black",
        linewidth=0.5,
    )

    cbar = plt.colorbar(scatter, ax=ax9, shrink=0.8)
    cbar.set_label("Sequencing Depth (Total Fragments)", rotation=270, labelpad=20)
    if np.max(depths) >= 1000:
        cbar.ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f"{x / 1000:.1f}K"))

    plt.xlabel(f"PC1 ({results['explained_variance'][0]:.1%})")
    plt.ylabel(f"PC2 ({results['explained_variance'][1]:.1%})")
    plt.title(f"{fragment_type} - Sequencing Depth Heatmap")
    plt.grid(True, alpha=0.3)

    corr_text = f"PC1-Depth: r={results['pc1_depth_correlation']:.3f}\nPC2-Depth: r={results['pc2_depth_correlation']:.3f}"
    plt.text(
        0.02,
        0.98,
        corr_text,
        transform=ax9.transAxes,
        verticalalignment="top",
        fontsize=9,
        bbox=dict(boxstyle="round", facecolor="white", alpha=0.9, edgecolor="black"),
    )

    plt.tight_layout(pad=2.0)
    ensure_output_directory()
    plot_file = os.path.join(OUTPUT_DIRECTORY, f"{fragment_type}_detailed_PCA_analysis.png")
    plt.savefig(plot_file, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"Saved detailed plot: {plot_file}")


def save_results_summary(all_results):
    """Save a comprehensive summary of all analyses."""
    ensure_output_directory()

    summary_file = os.path.join(OUTPUT_DIRECTORY, "PCA_analysis_summary.txt")
    with open(summary_file, "w") as f:
        f.write("=== cfDNA Detailed Size Bin PCA Analysis Summary ===\n\n")

        for fragment_type, results in all_results.items():
            if not results:
                f.write(f"{fragment_type}: No valid analysis\n\n")
                continue

            f.write(f"--- {fragment_type} Results ---\n")
            f.write(f"Samples analyzed: {results['X_pca'].shape[0]}\n")
            f.write(f"Size bins used: {len(results['size_columns'])}\n")
            f.write(f"Group source: {results['group_source']}\n")
            f.write(f"PC1 explained variance: {results['explained_variance'][0]:.1%}\n")
            f.write(f"PC2 explained variance: {results['explained_variance'][1]:.1%}\n")
            f.write(f"PC1+PC2 combined: {results['cumulative_variance'][1]:.1%}\n")

            if results["silhouette_score"] is not None:
                f.write(f"Silhouette score: {results['silhouette_score']:.3f}\n")

            f.write("\nStatistical significance tests:\n")
            for pc, stats in results["stats_results"].items():
                sig_level = "***" if stats["p_value"] < 0.001 else "**" if stats["p_value"] < 0.01 else "*" if stats["p_value"] < 0.05 else "ns"
                f.write(f"  {pc} [{stats.get('test', 'mwu')}]: p = {stats['p_value']:.4f} ({sig_level})\n")

            f.write("\nTop PC1 contributors:\n")
            if "PC1" in results["feature_contributions"]:
                for contrib in results["feature_contributions"]["PC1"]:
                    f.write(f"  {contrib['size_bin']}bp: {contrib['loading']:+.3f}\n")

            f.write("\nTop PC2 contributors:\n")
            if "PC2" in results["feature_contributions"]:
                for contrib in results["feature_contributions"]["PC2"]:
                    f.write(f"  {contrib['size_bin']}bp: {contrib['loading']:+.3f}\n")

            f.write("\n" + "=" * 50 + "\n\n")

    print(f"Analysis summary saved: {summary_file}")


def main():
    """Main analysis pipeline for detailed cfDNA size bin PCA."""
    global DATA_DIRECTORY, OUTPUT_DIRECTORY, FRAGMENT_TYPES, DROP_UNKNOWN_GROUP

    args = parse_args()
    DATA_DIRECTORY = args.data_dir
    OUTPUT_DIRECTORY = args.output_dir
    FRAGMENT_TYPES = [frag.strip() for frag in args.fragments.split(",") if frag.strip()]
    DROP_UNKNOWN_GROUP = bool(args.drop_unknown)

    print("=== Detailed cfDNA Size Bin PCA Analysis ===")
    print(f"Data directory: {DATA_DIRECTORY}")
    print(f"Output directory: {OUTPUT_DIRECTORY}")
    print(f"Fragment types: {FRAGMENT_TYPES}")
    print(f"Drop unknown groups: {DROP_UNKNOWN_GROUP}")

    if not os.path.exists(DATA_DIRECTORY):
        print(f"Error: Data directory not found: {DATA_DIRECTORY}")
        print("Please check path settings or pass --data-dir")
        return

    all_results = {}

    for fragment_type in FRAGMENT_TYPES:
        print(f"\n{'=' * 60}")
        print(f"Analyzing {fragment_type} fragments")
        print(f"{'=' * 60}")

        percentage_df, count_df = load_fragment_data(fragment_type)
        if percentage_df is None or count_df is None or percentage_df.empty or count_df.empty:
            print(f"Skipping {fragment_type} - no valid data")
            all_results[fragment_type] = None
            continue

        results = perform_fragment_pca(percentage_df, count_df, fragment_type)
        if results is None:
            print(f"Skipping {fragment_type} - PCA failed")
            all_results[fragment_type] = None
            continue

        all_results[fragment_type] = results
        create_comprehensive_plots(results)

    save_results_summary(all_results)

    print("\n=== Analysis Complete ===")
    print(f"Results saved in: {OUTPUT_DIRECTORY}")
    print("\nSummary:")
    for fragment_type, results in all_results.items():
        if results:
            pc1_var = results["explained_variance"][0]
            pc2_var = results["explained_variance"][1]
            n_samples = results["X_pca"].shape[0]
            n_bins = len(results["size_columns"])

            significant_pcs = []
            for pc, stats in results["stats_results"].items():
                if stats["p_value"] < 0.05:
                    significant_pcs.append(pc)

            print(f"  {fragment_type}: {n_samples} samples, {n_bins} size bins")
            print(f"    PC1: {pc1_var:.1%}, PC2: {pc2_var:.1%}")
            if significant_pcs:
                print(f"    Significant separation: {', '.join(significant_pcs)}")
            else:
                print("    No significant separation detected")
        else:
            print(f"  {fragment_type}: Analysis failed")


if __name__ == "__main__":
    main()
