#!/usr/bin/env python3
"""
Chromosome count ratio analysis for CSV files generated by chromosome_counts*.r.

This script is intentionally configuration-driven so it can be reused across cohorts.
Edit the USER SETTINGS block below for custom paths/grouping rules.
"""

import argparse
import glob
import os
import re
from itertools import combinations

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

# ============================================================================
# USER SETTINGS (edit these for your project)
# ============================================================================
# Directory containing chromosome_count table CSV files (recursive search).
INPUT_DIRECTORY = "/mnt/d/coronary_cfDNA"

# Output directory for figures and stats tables.
OUTPUT_DIRECTORY = "/mnt/d/coronary_cfDNA/chr_output"

# CSV file discovery pattern. Matches outputs from chromosome_counts*.r by default.
CSV_GLOB_PATTERNS = [
    "**/chromosome_counts_table_*.csv",
]

# Optional metadata CSV mapping sample IDs to groups.
# Set to None to infer groups from sample names using GROUP_RULES.
DEFAULT_SAMPLE_METADATA_CSV = None
DEFAULT_METADATA_SAMPLE_COL = "sample"
DEFAULT_METADATA_GROUP_COL = "group"

# Regex rules for inferring group labels from sample IDs when metadata is absent.
# Edit/extend these for your naming conventions.
GROUP_RULES = [
    {"label": "STEMI", "pattern": r"(?:^|[_-])cor(?:[_-]|$)"},
    {"label": "coronary", "pattern": r"(?:^|[_-])con(?:[_-]|$)"},
    {"label": "recovery", "pattern": r"(?:^|[_-])rec(?:[_-]|$)"},
]

# Preferred group ordering for plots. Unlisted groups are appended alphabetically.
GROUP_ORDER = ["STEMI", "coronary", "recovery", "unknown"]

# Optional fixed colors for known groups. New groups receive auto colors.
GROUP_COLOR_MAP = {
    "STEMI": "blue",
    "coronary": "red",
    "recovery": "green",
    "unknown": "gray",
}

# Set to True to keep unknown group samples in analysis.
KEEP_UNKNOWN_GROUPS = False
# ============================================================================


def parse_args():
    """Parse CLI args to override settings without editing the script."""
    parser = argparse.ArgumentParser(description="Chromosome ratio statistics from chromosome_counts tables")
    parser.add_argument("--input-dir", default=INPUT_DIRECTORY, help="Input directory (recursive)")
    parser.add_argument("--output-dir", default=OUTPUT_DIRECTORY, help="Output directory")
    parser.add_argument(
        "--sample-metadata-csv",
        default=DEFAULT_SAMPLE_METADATA_CSV,
        help="Optional metadata CSV with sample->group mapping",
    )
    parser.add_argument(
        "--metadata-sample-col",
        default=DEFAULT_METADATA_SAMPLE_COL,
        help="Sample ID column in metadata CSV",
    )
    parser.add_argument(
        "--metadata-group-col",
        default=DEFAULT_METADATA_GROUP_COL,
        help="Group column in metadata CSV",
    )
    parser.add_argument(
        "--keep-unknown",
        action="store_true",
        default=KEEP_UNKNOWN_GROUPS,
        help="Keep unknown-group samples",
    )
    return parser.parse_args()


def normalize_runtime_path(path_str: str) -> str:
    """Normalize path style between Windows and WSL/POSIX paths."""
    path_str = str(path_str)

    if os.name == "nt" and path_str.startswith("/mnt/"):
        parts = path_str.split("/")
        if len(parts) >= 4 and len(parts[2]) == 1:
            drive = parts[2].upper() + ":"
            tail = parts[3:]
            return os.path.join(drive + os.sep, *tail)

    if os.name != "nt" and re.match(r"^[A-Za-z]:[\\/]", path_str):
        drive = path_str[0].lower()
        rest = path_str[2:].replace("\\", "/").lstrip("/")
        return f"/mnt/{drive}/{rest}"

    return path_str


def ensure_output_directory(path):
    """Create output directory if it doesn't exist."""
    os.makedirs(path, exist_ok=True)


def p_to_stars(p_val: float) -> str:
    if pd.isna(p_val):
        return ""
    if p_val < 0.001:
        return "***"
    if p_val < 0.01:
        return "**"
    if p_val < 0.05:
        return "*"
    return ""


def get_ordered_groups(groups):
    observed = set(groups)
    ordered = [g for g in GROUP_ORDER if g in observed]
    remaining = sorted([g for g in observed if g not in GROUP_ORDER])
    return ordered + remaining


def build_group_color_map(groups):
    color_map = dict(GROUP_COLOR_MAP)
    extras = [g for g in get_ordered_groups(groups) if g not in color_map]
    if extras:
        palette = plt.cm.tab20(np.linspace(0, 1, max(3, len(extras))))
        for idx, group in enumerate(extras):
            rgb = palette[idx % len(palette)][:3]
            color_map[group] = "#%02x%02x%02x" % tuple(int(255 * c) for c in rgb)
    return color_map


def discover_csv_files(input_directory):
    """Discover chromosome count table CSVs recursively using CSV_GLOB_PATTERNS."""
    csv_files = []
    for pattern in CSV_GLOB_PATTERNS:
        csv_files.extend(glob.glob(os.path.join(input_directory, pattern), recursive=True))
    csv_files = sorted(set(csv_files))

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {input_directory} using patterns: {CSV_GLOB_PATTERNS}")

    print(f"Found {len(csv_files)} CSV files:")
    for file in csv_files:
        print(f"  - {os.path.basename(file)}")

    return csv_files


def parse_sample_id_from_filename(file_path):
    """Extract sample ID from chromosome_counts table filename."""
    filename = os.path.basename(file_path)
    # canonical format: chromosome_counts_table_<sample>.csv
    m = re.match(r"chromosome_counts_table_(.+?)\.csv$", filename, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    # fallback: filename without extension
    return os.path.splitext(filename)[0]


def infer_group_from_sample_name(sample_name):
    """Infer group label using GROUP_RULES regex rules."""
    name = str(sample_name).lower()
    for rule in GROUP_RULES:
        if re.search(rule["pattern"], name):
            return str(rule["label"])
    return "unknown"


def load_group_map(metadata_csv, sample_col, group_col):
    """Load optional sample->group mapping metadata."""
    if metadata_csv is None:
        return None

    if not os.path.exists(metadata_csv):
        raise FileNotFoundError(f"Metadata CSV not found: {metadata_csv}")

    meta_df = pd.read_csv(metadata_csv)
    if sample_col not in meta_df.columns or group_col not in meta_df.columns:
        raise ValueError(f"Metadata CSV must contain columns '{sample_col}' and '{group_col}'")

    mapping = {}
    for _, row in meta_df[[sample_col, group_col]].dropna().iterrows():
        key = str(row[sample_col]).strip()
        mapping[key] = str(row[group_col]).strip()

    return mapping


def assign_group(sample_id, group_map=None):
    """Assign group from metadata map if available, else infer from sample name."""
    if group_map is not None and sample_id in group_map:
        return group_map[sample_id], "metadata"
    return infer_group_from_sample_name(sample_id), "inferred"


def read_one_csv(file_path):
    """Read one chromosome_count table robustly across delimiter/decimal conventions."""
    delimiters = [",", ";", "\t"]
    for delimiter in delimiters:
        for decimal in [",", "."]:
            try:
                df = pd.read_csv(file_path, sep=delimiter, decimal=decimal)
                if df.shape[1] >= 3:
                    return df
            except Exception:
                pass

    # fallback auto-detect
    for decimal in [",", "."]:
        try:
            df = pd.read_csv(file_path, sep=None, engine="python", decimal=decimal)
            if df.shape[1] >= 3:
                return df
        except Exception:
            pass

    raise ValueError("Could not parse CSV with known delimiter/decimal combinations")


def extract_chr1_22_ratios(df):
    """Extract 22 autosomal chromosome percentages from an input dataframe."""
    if len(df) < 23 or df.shape[1] < 3:
        raise ValueError(f"Insufficient shape: rows={len(df)}, cols={df.shape[1]}")

    max_rows = min(40, len(df))
    labels_from_0 = df.iloc[0:max_rows, 0].values if len(df) > 0 else []
    ratios_from_0 = df.iloc[0:max_rows, 2].values if len(df) > 0 else []

    labels_from_1 = df.iloc[1:max_rows, 0].values if len(df) > 1 else []
    ratios_from_1 = df.iloc[1:max_rows, 2].values if len(df) > 1 else []

    def parse_chrom_num(label):
        s = str(label).strip().lower()
        if s.isdigit():
            return int(s)
        if s.startswith("chr") and len(s) > 3:
            t = s[3:].strip()
            if t.isdigit():
                return int(t)
        return None

    def count_valid(labels):
        nums = []
        for label in labels:
            n = parse_chrom_num(label)
            if n is not None and 1 <= n <= 22:
                nums.append(n)
        return len(nums), nums

    count_0, nums_0 = count_valid(labels_from_0)
    count_1, nums_1 = count_valid(labels_from_1)

    if count_0 >= count_1 and count_0 >= 22:
        all_labels = labels_from_0
        all_ratios = ratios_from_0
    elif count_1 >= 22:
        all_labels = labels_from_1
        all_ratios = ratios_from_1
    else:
        raise ValueError("Could not detect 22 autosomes in either row-offset format")

    valid_indices = []
    for i, label in enumerate(all_labels):
        n = parse_chrom_num(label)
        if n is not None and 1 <= n <= 22:
            valid_indices.append((n, i))

    # deduplicate by chromosome number, keep first occurrence
    chr_to_idx = {}
    for chrom_num, idx in valid_indices:
        if chrom_num not in chr_to_idx:
            chr_to_idx[chrom_num] = idx

    if len(chr_to_idx) != 22:
        raise ValueError(f"Expected 22 autosomes, found {len(chr_to_idx)}")

    ordered_indices = [chr_to_idx[c] for c in range(1, 23)]
    ratios = pd.to_numeric(np.array(all_ratios)[ordered_indices], errors="coerce")

    if np.any(pd.isna(ratios)):
        raise ValueError("NaN values in extracted chromosome ratios")

    if np.sum(ratios) <= 0:
        raise ValueError("Extracted ratios sum to zero")

    # Normalize to percentages for robustness
    ratios = (ratios / np.sum(ratios)) * 100.0
    return ratios


def read_chromosome_data(input_directory, group_map=None, keep_unknown=False):
    """Read chromosome CSV files and return per-group matrices and sample metadata."""
    csv_files = discover_csv_files(input_directory)

    data = {}
    sample_info = []

    for file_path in csv_files:
        filename = os.path.basename(file_path)
        sample_id = parse_sample_id_from_filename(file_path)
        sample_group, group_source = assign_group(sample_id, group_map=group_map)

        if sample_group == "unknown" and not keep_unknown:
            print(f"Skipping unknown sample group: {filename}")
            continue

        try:
            df = read_one_csv(file_path)
            chromosome_ratios = extract_chr1_22_ratios(df)

            data.setdefault(sample_group, []).append(chromosome_ratios)
            sample_info.append(
                {
                    "sample_id": sample_id,
                    "filename": filename,
                    "group": sample_group,
                    "group_source": group_source,
                }
            )
        except Exception as e:
            print(f"Warning: failed to parse {filename}: {e}")

    if not data:
        raise ValueError("No valid sample data parsed")

    for group in list(data.keys()):
        data[group] = np.array(data[group])

    ordered_groups = get_ordered_groups(data.keys())
    data = {g: data[g] for g in ordered_groups if g in data}

    for group, arr in data.items():
        print(f"Loaded {len(arr)} samples for group '{group}'")

    return data, pd.DataFrame(sample_info)


def calculate_mean_ratios(data):
    """Calculate mean chromosome ratios for each sample type."""
    mean_ratios = {}
    for sample_type, samples in data.items():
        mean_ratios[sample_type] = np.mean(samples, axis=0)
    return mean_ratios


def create_line_plot(mean_ratios, data, output_directory):
    """Create line plot comparing average chromosome ratios."""
    chromosomes = np.arange(1, 23)

    plt.figure(figsize=(12, 6))

    ordered_groups = get_ordered_groups([g for g in mean_ratios.keys() if len(mean_ratios[g]) > 0])
    color_map = build_group_color_map(ordered_groups)
    marker_cycle = ["o", "s", "^", "D", "P", "X", "v", "<", ">"]

    for idx, sample_type in enumerate(ordered_groups):
        if sample_type in mean_ratios and len(mean_ratios[sample_type]) > 0:
            sample_count = len(data[sample_type]) if sample_type in data else 0
            plt.plot(
                chromosomes,
                mean_ratios[sample_type],
                marker=marker_cycle[idx % len(marker_cycle)],
                linewidth=2.5,
                label=f"{sample_type} (n={sample_count})",
                markersize=6,
                color=color_map.get(sample_type, "gray"),
                alpha=0.9,
            )

    plt.xlabel("Chromosome", fontsize=12)
    plt.ylabel("cfDNA Ratio per chromosome (%)", fontsize=12)
    plt.title("Average Chromosome origins of cfDNA by group", fontsize=14, fontweight="bold")
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.xticks(chromosomes)
    plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: "{:.0f}%".format(y)))

    plt.tight_layout()

    output_path = os.path.join(output_directory, "chromosome_ratios_line_plot.png")
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Line plot saved to: {output_path}")


def kolmogorov_smirnov_test(data):
    """Perform pairwise Kolmogorov-Smirnov tests across groups."""
    available_groups = [g for g in get_ordered_groups(data.keys()) if len(data[g]) > 0]
    if len(available_groups) < 2:
        print("Cannot perform KS tests: fewer than two groups have data")
        return None

    print("\n" + "=" * 50)
    print("PAIRWISE KOLMOGOROV-SMIRNOV TEST RESULTS")
    print("=" * 50)
    ks_results = []
    for group_a, group_b in combinations(available_groups, 2):
        group_a_all = data[group_a].flatten()
        group_b_all = data[group_b].flatten()
        group_a_all = group_a_all[~np.isnan(group_a_all)]
        group_b_all = group_b_all[~np.isnan(group_b_all)]

        ks_statistic, ks_p_value = stats.ks_2samp(group_a_all, group_b_all)
        ks_results.append((group_a, group_b, ks_statistic, ks_p_value))

        print(f"{group_a} vs {group_b}")
        print(f"  KS Statistic: {ks_statistic:.4f}")
        print(f"  P-value: {ks_p_value:.4e} {p_to_stars(ks_p_value)}")
        print(f"  Significant difference (p < 0.05): {ks_p_value < 0.05}")
    print("=" * 50)

    return ks_results


def mann_whitney_u_tests(data):
    """Perform pairwise Mann-Whitney U tests for each chromosome across groups."""
    available_groups = [g for g in get_ordered_groups(data.keys()) if len(data[g]) > 0]
    if len(available_groups) < 2:
        print("Cannot perform Mann-Whitney U tests: fewer than two groups have data")
        return [], []

    chromosomes = np.arange(1, 23)
    significant_chromosomes = []
    results = []

    print("\n" + "=" * 70)
    print("MANN-WHITNEY U TEST RESULTS (per chromosome)")
    print("=" * 70)
    print(f"{'Chromosome':<12} {'U-statistic':<12} {'P-value':<12} {'Significant':<12}")
    print("-" * 70)

    for i, chrom in enumerate(chromosomes):
        chrom_has_significant_pair = False
        for group_a, group_b in combinations(available_groups, 2):
            group_a_chrom = data[group_a][:, i]
            group_b_chrom = data[group_b][:, i]

            group_a_chrom = group_a_chrom[~np.isnan(group_a_chrom)]
            group_b_chrom = group_b_chrom[~np.isnan(group_b_chrom)]

            if len(group_a_chrom) < 2 or len(group_b_chrom) < 2:
                print(f"{chrom:<12} {'N/A':<12} {'N/A':<12} {'Insufficient':<12} ({group_a} vs {group_b})")
                continue

            try:
                u_statistic, p_value = stats.mannwhitneyu(group_a_chrom, group_b_chrom, alternative="two-sided")
                is_significant = p_value < 0.05

                results.append(
                    {
                        "chromosome": chrom,
                        "group_a": group_a,
                        "group_b": group_b,
                        "u_statistic": u_statistic,
                        "p_value": p_value,
                        "significant": is_significant,
                        "stars": p_to_stars(p_value),
                    }
                )

                chrom_has_significant_pair = chrom_has_significant_pair or is_significant
                pair_label = f"({group_a} vs {group_b})"
                print(f"{chrom:<12} {u_statistic:<12.2f} {p_value:<12.4e} {str(is_significant):<12} {p_to_stars(p_value)} {pair_label}")

            except Exception as e:
                print(f"{chrom:<12} {'Error':<12} {'Error':<12} {str(e)[:20]:<12} ({group_a} vs {group_b})")

        if chrom_has_significant_pair and chrom not in significant_chromosomes:
            significant_chromosomes.append(chrom)

    print("=" * 70)
    print(f"Significant chromosomes (p < 0.05): {significant_chromosomes}")
    print("=" * 70)

    return results, significant_chromosomes


def create_boxplots_for_significant_chromosomes(data, results, significant_chromosomes, output_directory):
    """Create boxplots for chromosomes with significant differences."""
    if not significant_chromosomes:
        print("No significant chromosomes found. No boxplots will be created.")
        return

    print(f"\nCreating boxplots for {len(significant_chromosomes)} significant chromosomes...")

    available_groups = [g for g in get_ordered_groups(data.keys()) if len(data[g]) > 0]
    color_map = build_group_color_map(available_groups)

    for chrom in significant_chromosomes:
        chrom_results = [r for r in results if r["chromosome"] == chrom]
        if not chrom_results:
            continue

        group_series = []
        group_labels = []
        for group in available_groups:
            values = data[group][:, chrom - 1]
            values = values[~np.isnan(values)]
            if len(values) == 0:
                continue
            group_series.append(values)
            group_labels.append(group)

        if len(group_series) < 2:
            continue

        plt.figure(figsize=(10, 6))
        box_plot = plt.boxplot(group_series, labels=group_labels, patch_artist=True)

        for patch, group in zip(box_plot["boxes"], group_labels):
            patch.set_facecolor(color_map.get(group, "lightgray"))
            patch.set_alpha(0.35)

        for idx, group in enumerate(group_labels, start=1):
            values = group_series[idx - 1]
            plt.scatter(
                [idx] * len(values),
                values,
                alpha=0.6,
                color=color_map.get(group, "gray"),
                s=30,
                label=f"{group} samples",
            )

        y_max = max(np.max(values) for values in group_series)
        y_min = min(np.min(values) for values in group_series)
        y_range = y_max - y_min if y_max > y_min else max(abs(y_max), 1.0)

        significance_height = y_max + 0.1 * y_range
        plt.plot([1, len(group_labels)], [significance_height, significance_height], "k-", linewidth=1)
        plt.plot([1, 1], [significance_height - 0.02 * y_range, significance_height], "k-", linewidth=1)
        plt.plot([len(group_labels), len(group_labels)], [significance_height - 0.02 * y_range, significance_height], "k-", linewidth=1)

        p_val = min(r["p_value"] for r in chrom_results)
        star_text = p_to_stars(p_val) if p_to_stars(p_val) else "ns"
        mid_x = (1 + len(group_labels)) / 2
        plt.text(mid_x, significance_height + 0.02 * y_range, star_text, ha="center", va="bottom", fontsize=16, fontweight="bold")

        plt.ylabel("cfDNA Ratio (%)", fontsize=12)
        plt.xlabel("Sample Type", fontsize=12)
        plt.title(f"Chromosome {chrom} cfDNA Ratios\n(min pairwise p = {p_val:.4e})", fontsize=14, fontweight="bold")
        plt.grid(True, alpha=0.3)
        plt.legend(fontsize=9)
        plt.tight_layout()

        output_path = os.path.join(output_directory, f"chromosome_{chrom}_boxplot.png")
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
        plt.close()
        print(f"Boxplot for chromosome {chrom} saved to: {output_path}")


def save_statistical_results(ks_results, mw_results, significant_chromosomes, output_directory, sample_info_df):
    """Save statistical test results and sample mapping to text/CSV files."""
    text_path = os.path.join(output_directory, "statistical_results.txt")
    mw_csv_path = os.path.join(output_directory, "mann_whitney_results.csv")
    sample_csv_path = os.path.join(output_directory, "sample_group_assignments.csv")

    mw_df = pd.DataFrame(mw_results)
    if not mw_df.empty:
        mw_df.to_csv(mw_csv_path, index=False)
    sample_info_df.to_csv(sample_csv_path, index=False)

    with open(text_path, "w") as f:
        f.write("CHROMOSOME cfDNA RATIO ANALYSIS RESULTS\n")
        f.write("=" * 60 + "\n\n")

        if ks_results:
            f.write("PAIRWISE KOLMOGOROV-SMIRNOV TESTS\n")
            f.write("-" * 40 + "\n")
            for group_a, group_b, ks_statistic, ks_p_value in ks_results:
                f.write(
                    f"{group_a} vs {group_b}: KS={ks_statistic:.4f}, p={ks_p_value:.4e} {p_to_stars(ks_p_value)}, "
                    f"significant={ks_p_value < 0.05}\n"
                )
            f.write("\n")

        f.write("MANN-WHITNEY U TESTS (per chromosome)\n")
        f.write("-" * 50 + "\n")
        if mw_df.empty:
            f.write("No MWU results available\n")
        else:
            for _, row in mw_df.iterrows():
                f.write(
                    f"Chr{int(row['chromosome'])}: {row['group_a']} vs {row['group_b']}, "
                    f"U={row['u_statistic']:.2f}, p={row['p_value']:.4e} {row['stars']}\n"
                )

        f.write(f"\nSignificant chromosomes (p < 0.05): {significant_chromosomes}\n")
        f.write(f"Total significant chromosomes: {len(significant_chromosomes)}\n")

    print(f"Statistical text results saved to: {text_path}")
    if not mw_df.empty:
        print(f"Mann-Whitney results CSV saved to: {mw_csv_path}")
    print(f"Sample/group assignments saved to: {sample_csv_path}")


def main():
    """Main analysis pipeline."""
    args = parse_args()

    input_directory = normalize_runtime_path(args.input_dir)
    output_directory = normalize_runtime_path(args.output_dir)
    metadata_csv = normalize_runtime_path(args.sample_metadata_csv) if args.sample_metadata_csv else None

    print("Starting Chromosome cfDNA Ratio Analysis...")
    print(f"Input directory: {input_directory}")
    print(f"Output directory: {output_directory}")
    print(f"Metadata CSV: {metadata_csv}")

    ensure_output_directory(output_directory)

    try:
        group_map = load_group_map(
            metadata_csv,
            sample_col=args.metadata_sample_col,
            group_col=args.metadata_group_col,
        )

        data, sample_info_df = read_chromosome_data(
            input_directory,
            group_map=group_map,
            keep_unknown=bool(args.keep_unknown),
        )

        if len(data) < 2:
            raise ValueError("Need at least 2 groups with data for comparative stats")

        mean_ratios = calculate_mean_ratios(data)
        create_line_plot(mean_ratios, data, output_directory)

        ks_results = kolmogorov_smirnov_test(data)
        mw_results, significant_chromosomes = mann_whitney_u_tests(data)

        create_boxplots_for_significant_chromosomes(
            data,
            mw_results,
            significant_chromosomes,
            output_directory,
        )

        save_statistical_results(
            ks_results,
            mw_results,
            significant_chromosomes,
            output_directory,
            sample_info_df,
        )

        print(f"\nAnalysis complete! All outputs saved to: {output_directory}")

    except Exception as e:
        print(f"Error during analysis: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
